language: scala
scala:
   - "2.9.2"
jdk:
   - oraclejdk7
   - openjdk7
env: 
   - SBT_OPTS="-Xms1536m -Xmx1536m -XX:MaxPermSize=384m -XX:ReservedCodeCacheSize=192m"
install: ./setup.sh
script: sbt/bin/sbt test 
